version: '3'

services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./docker/mysql:/etc/mysql/conf.d
    ports:
      - ${DB_PORT}:3306
