version: '3'

services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./docker/mysql:/etc/mysql/conf.d
    ports:
      - 3306:3306
